package View;

import Controller.constroiTabelaAtleta;
import Controller.deletaAtleta;
import Controller.pesquisaAtleta;
import Controller.pesquisaCompeticao;
import Controller.pesquisaEquipe;
import Model.Atleta;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel
 */
public class FrameAtletas extends javax.swing.JFrame {

    DefaultTableModel model;
    Atleta cliente = new Atleta();

    /**
     * Creates new form Atletas
     *
     * @throws java.sql.SQLException
     */
    public FrameAtletas() throws SQLException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelListagem = new javax.swing.JPanel();
        tbCRUD = new javax.swing.JToolBar();
        btAdicionar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        ftfPesquisar = new javax.swing.JFormattedTextField();
        spAtletas = new javax.swing.JScrollPane();
        tableListagem = new javax.swing.JTable();
        btVoltar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        lbNomeCompeticao = new javax.swing.JLabel();
        btRelatorio = new javax.swing.JButton();
        mbBarraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atletas");

        painelListagem.setBorder(javax.swing.BorderFactory.createTitledBorder("ATLETAS"));

        tbCRUD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbCRUD.setFloatable(false);

        btAdicionar.setText("Adicionar");
        btAdicionar.setFocusable(false);
        btAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAdicionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        tbCRUD.add(btAdicionar);

        btAlterar.setText("Alterar");
        btAlterar.setFocusable(false);
        btAlterar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAlterar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        tbCRUD.add(btAlterar);

        btRemover.setText("Remover");
        btRemover.setFocusable(false);
        btRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        tbCRUD.add(btRemover);

        btPesquisar.setText("Pesquisar");
        btPesquisar.setFocusable(false);
        btPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        tbCRUD.add(btPesquisar);

        try {
            ftfPesquisar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfPesquisar.setPreferredSize(new java.awt.Dimension(100, 30));
        ftfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfPesquisarActionPerformed(evt);
            }
        });
        tbCRUD.add(ftfPesquisar);

        tableListagem.setAutoCreateRowSorter(true);
        tableListagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableListagem.setAutoscrolls(false);
        tableListagem.getTableHeader().setReorderingAllowed(false);
        spAtletas.setViewportView(tableListagem);

        javax.swing.GroupLayout painelListagemLayout = new javax.swing.GroupLayout(painelListagem);
        painelListagem.setLayout(painelListagemLayout);
        painelListagemLayout.setHorizontalGroup(
            painelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbCRUD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(spAtletas)
        );
        painelListagemLayout.setVerticalGroup(
            painelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelListagemLayout.createSequentialGroup()
                .addComponent(tbCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btVoltar.setText("Voltar");
        btVoltar.setPreferredSize(new java.awt.Dimension(100, 30));
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.setPreferredSize(new java.awt.Dimension(100, 30));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        lbNomeCompeticao.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNomeCompeticao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btRelatorio.setText("Relatório");
        btRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioActionPerformed(evt);
            }
        });

        menuArquivo.setText("Arquivo");
        mbBarraMenu.add(menuArquivo);

        menuAjuda.setText("Ajuda");
        mbBarraMenu.add(menuAjuda);

        setJMenuBar(mbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btRelatorio)
                        .addGap(201, 201, 201)
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbNomeCompeticao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeCompeticao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(painelListagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRelatorio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
        FrameSelecaoPrincipal frameSelecao = new FrameSelecaoPrincipal();
        frameSelecao.lbNomeCompeticao.setText((String) this.lbNomeCompeticao.getText());
        frameSelecao.setVisible(true);

    }//GEN-LAST:event_btVoltarActionPerformed
    /*public DefaultTableModel montaTabela() {
        model = new DefaultTableModel(new Object[][]{},
                new String[]{
                    "Código", "Nome", "Categoria", "Equipe"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tableListagem.getTableHeader().setReorderingAllowed(false);
        tableListagem.setAutoCreateRowSorter(true);
        tableListagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableListagem.setModel(model);
        tableListagem.setAutoscrolls(false);

        spAtletas.setViewportView(tableListagem);
        return model;
    }*/
    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        try {
            FrameAdicionaAtleta frameAtleta = new FrameAdicionaAtleta();
            frameAtleta.lbNomeCompeticao.setText(this.lbNomeCompeticao.getText());
            int codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            ArrayList<String> equipes = pesquisaEquipe.carregaComboBoxEquipes(codCompeticao);
            for (int i = 0; i < equipes.size(); i++) {
                frameAtleta.cbEquipe.addItem(equipes.get(i));
            }
            frameAtleta.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtletas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrameAtletas.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed

        try {
            int codAtleta = pesquisaAtleta.validaLinhaSelecionada(tableListagem);
            ResultSet rs = pesquisaAtleta.pesquisaAtleta(codAtleta);

            FrameAlteraAtleta frameAtleta = new FrameAlteraAtleta();
            frameAtleta.lbNomeCompeticao.setText(this.lbNomeCompeticao.getText());

            while (rs.next()) {
                frameAtleta.ftfCpf.setText(rs.getString("Cpf"));
                frameAtleta.ftfCpf.setEnabled(false);
                frameAtleta.tfNome.setText(rs.getString("Nome"));
                frameAtleta.tfEndereco.setText(rs.getString("Endereco"));
                frameAtleta.ftfDtNascimento.setText(rs.getString("Dtnascimento"));
                frameAtleta.cbEstado.setSelectedItem(rs.getString("Estado"));
                frameAtleta.cbCidade.setSelectedItem(rs.getString("Cidade"));
                frameAtleta.cbStatus.setSelectedItem(rs.getString("Status"));
                frameAtleta.rbMasculino.setSelected(rs.getString("Sexo").equals("Masculino"));
                frameAtleta.rbFeminino.setSelected(rs.getString("Sexo").equals("Feminino"));
                frameAtleta.cbEquipe.setSelectedItem(rs.getString("Nomeequipe"));
            }

            int codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            ArrayList<String> equipes = pesquisaEquipe.carregaComboBoxEquipes(codCompeticao);
            for (int i = 0; i < equipes.size(); i++) {
                frameAtleta.cbEquipe.addItem(equipes.get(i));
            }
            
            frameAtleta.setVisible(true);
            this.dispose();

        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Selecine um atleta.");
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtletas.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        try {
            int codAtleta = pesquisaAtleta.validaLinhaSelecionada(tableListagem);
            deletaAtleta.deletarAtleta(codAtleta);
            int codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            remove(this.tableListagem);
            DefaultTableModel model = constroiTabelaAtleta.estruturaTabelaAtleta(this.tableListagem, this.spAtletas);
            pesquisaAtleta.carregaJTableAtletas(model, codCompeticao);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Selecine um atleta.");
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtletas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrameAtletas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        try {
            DefaultTableModel model = constroiTabelaAtleta.estruturaTabelaAtleta(this.tableListagem, this.spAtletas);
            String cpf = ftfPesquisar.getText();
            pesquisaAtleta.pesquisaAtleta(model, cpf);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAtletas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void ftfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfPesquisarActionPerformed

    private void btRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioActionPerformed
        ResultSet rs;
        try {
            int codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            rs = pesquisaAtleta.pesquisaTodosAtleta(codCompeticao);
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperPrint jp;
            jp = JasperFillManager.fillReport("C:\\Users\\dnlhi\\Dropbox\\FATEC\\2017\\2º Semestre\\Programação Orientada a Objetos Avançada\\NetBeansProjects\\Projeto\\SCN\\relatorio\\MyReports\\atletas.jasper", null, jrRS);
            JasperViewer relatorio = new JasperViewer(jp, false);
            relatorio.setVisible(true);
            relatorio.toFront();
        } catch (SQLException | JRException ex) {
            Logger.getLogger(FrameSelecaoPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAtletas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameAtletas().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameAtletas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVoltar;
    private javax.swing.JFormattedTextField ftfPesquisar;
    public javax.swing.JLabel lbNomeCompeticao;
    private javax.swing.JMenuBar mbBarraMenu;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JPanel painelListagem;
    public javax.swing.JScrollPane spAtletas;
    public javax.swing.JTable tableListagem;
    private javax.swing.JToolBar tbCRUD;
    // End of variables declaration//GEN-END:variables

    /*private void carregaTabelaAtletaPesquisado() throws SQLException {
        String cpf = ftfPesquisar.getText();
        model = montaTabela();
        pesquisaAtleta.pesquisaAtleta(model, cpf);
    }*/
}
