package View;

import Controller.pesquisaBateria;
import Controller.pesquisaCompeticao;
import Controller.pesquisaCompetidor;
import Controller.pesquisaModalidade;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dnlhi
 */
public class FrameSelecaoModalidade extends javax.swing.JFrame {

    /**
     * Creates new form FrameModalidades
     */
    public FrameSelecaoModalidade() throws SQLException {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSelecao = new javax.swing.JPanel();
        btSelecionarModalidade = new javax.swing.JButton();
        lbVoltar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        cbModalidade = new javax.swing.JComboBox<>();
        btCadastrarModalidade = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbNomeCompeticao = new javax.swing.JLabel();
        mbModalidade = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelSelecao.setBorder(javax.swing.BorderFactory.createTitledBorder("MODALIDADES"));

        btSelecionarModalidade.setText("SELECIONAR");
        btSelecionarModalidade.setPreferredSize(new java.awt.Dimension(120, 40));
        btSelecionarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarModalidadeActionPerformed(evt);
            }
        });

        lbVoltar.setText("Voltar");
        lbVoltar.setPreferredSize(new java.awt.Dimension(70, 30));
        lbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbVoltarActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.setPreferredSize(new java.awt.Dimension(70, 30));

        cbModalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE A MODALIDADE" }));
        cbModalidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbModalidadeMouseClicked(evt);
            }
        });

        btCadastrarModalidade.setText("CADASTRAR MODALIDADE");
        btCadastrarModalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarModalidadeActionPerformed(evt);
            }
        });

        jButton1.setText("Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSelecaoLayout = new javax.swing.GroupLayout(painelSelecao);
        painelSelecao.setLayout(painelSelecaoLayout);
        painelSelecaoLayout.setHorizontalGroup(
            painelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelecaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(painelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSelecaoLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(btSelecionarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelSelecaoLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)
                        .addGap(77, 77, 77)
                        .addComponent(btCadastrarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(painelSelecaoLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(cbModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        painelSelecaoLayout.setVerticalGroup(
            painelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelecaoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(cbModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSelecionarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(painelSelecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrarModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        lbNomeCompeticao.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNomeCompeticao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menuArquivo.setText("Arquivo");
        mbModalidade.add(menuArquivo);

        menuAjuda.setText("Ajuda");
        mbModalidade.add(menuAjuda);

        setJMenuBar(mbModalidade);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSelecao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNomeCompeticao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeCompeticao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(painelSelecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSelecionarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarModalidadeActionPerformed
        int codModalidade, numBaterias, codCompeticao;
        if (this.cbModalidade.getSelectedItem().equals("SELECIONE A MODALIDADE") || this.cbModalidade.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(this, "Selecione a modalidade");
        } else {
            try {
                String nomeModalidade = (String) this.cbModalidade.getSelectedItem();
                FrameSelecaoBateria frameBateria = new FrameSelecaoBateria();
                frameBateria.lbNomeCompeticao.setText((String) this.lbNomeCompeticao.getText());
                frameBateria.setName(nomeModalidade);
                codModalidade = pesquisaModalidade.pesquisaModalidade(nomeModalidade);
                codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
                numBaterias = pesquisaBateria.qtdBaterias(codModalidade, codCompeticao);
                for (int i = 1; i <= numBaterias; i++) {
                    if (i == numBaterias) {
                        frameBateria.cbBaterias.addItem("Final");
                    } else {
                        frameBateria.cbBaterias.addItem(Integer.toString(i));
                    }
                }
                frameBateria.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }

    }//GEN-LAST:event_btSelecionarModalidadeActionPerformed

    private void lbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbVoltarActionPerformed
        FrameSelecaoPrincipal frameSelecao = new FrameSelecaoPrincipal();
        frameSelecao.lbNomeCompeticao.setText(this.lbNomeCompeticao.getText());
        frameSelecao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbVoltarActionPerformed

    private void btCadastrarModalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarModalidadeActionPerformed
        FrameAdicionaModalidade frameModalidade = new FrameAdicionaModalidade();
        frameModalidade.lbNomeCompeticao.setText(this.lbNomeCompeticao.getText());
        frameModalidade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCadastrarModalidadeActionPerformed

    private void cbModalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbModalidadeMouseClicked
        /*this.cbModalidade.removeAllItems();
        int codCompeticao;
        try {
            codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            ArrayList<String> modalidades = pesquisaModalidade.carregaComboBoxModalidade(codCompeticao);
            for (int i = 0; i < modalidades.size(); i++) {
                cbModalidade.addItem(modalidades.get(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(Level.SEVERE, null, ex);
        }*/

    }//GEN-LAST:event_cbModalidadeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet rs;
        try {
            int codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            rs = pesquisaCompetidor.relatorioCompetidoresModalidade(codCompeticao);
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperPrint jp;
            jp = JasperFillManager.fillReport("C:\\Users\\dnlhi\\Dropbox\\FATEC\\2017\\2º Semestre\\Programação Orientada a Objetos Avançada\\NetBeansProjects\\Projeto\\SCN\\relatorio\\MyReports\\competidoresPorModalidade.jasper", null, jrRS);
            JasperViewer relatorio = new JasperViewer(jp, false);
            relatorio.setVisible(true);
            relatorio.toFront();
        } catch (SQLException | JRException ex) {
            Logger.getLogger(FrameSelecaoPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrameBateria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameSelecaoModalidade().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameSelecaoModalidade.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarModalidade;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSelecionarModalidade;
    public javax.swing.JComboBox<String> cbModalidade;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel lbNomeCompeticao;
    private javax.swing.JButton lbVoltar;
    private javax.swing.JMenuBar mbModalidade;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JPanel painelSelecao;
    // End of variables declaration//GEN-END:variables
}
