package View;


import Controller.gravaAtleta;
import Controller.pesquisaAtleta;
import Controller.pesquisaEquipe;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel
 */
public class FrameIncluirAtletaEquipe extends javax.swing.JFrame {

    /**
     * Creates new form FrameIncluirAtletaEquipe
     */
    public FrameIncluirAtletaEquipe() throws SQLException {
        initComponents();
        this.cbAtleta1.setEnabled(false);
        this.cbAtleta2.setEnabled(false);
        this.cbAtleta3.setEnabled(false);
        this.cbAtleta4.setEnabled(false);
        this.cbAtleta5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelIncluirAtletas = new javax.swing.JPanel();
        lbAtleta1 = new javax.swing.JLabel();
        lbAtleta2 = new javax.swing.JLabel();
        lbAtleta3 = new javax.swing.JLabel();
        lbAtleta4 = new javax.swing.JLabel();
        lbAtleta5 = new javax.swing.JLabel();
        cbAtleta1 = new javax.swing.JComboBox<>();
        cbAtleta2 = new javax.swing.JComboBox<>();
        cbAtleta3 = new javax.swing.JComboBox<>();
        cbAtleta4 = new javax.swing.JComboBox<>();
        cbAtleta5 = new javax.swing.JComboBox<>();
        tfAtleta1 = new javax.swing.JTextField();
        tfAtleta2 = new javax.swing.JTextField();
        tfAtleta3 = new javax.swing.JTextField();
        tfAtleta4 = new javax.swing.JTextField();
        tfAtleta5 = new javax.swing.JTextField();
        chkAtleta1 = new javax.swing.JCheckBox();
        chkAtleta2 = new javax.swing.JCheckBox();
        chkAtleta3 = new javax.swing.JCheckBox();
        chkAtleta4 = new javax.swing.JCheckBox();
        chkAtleta5 = new javax.swing.JCheckBox();
        btIncluir = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbNomeEquipe = new javax.swing.JLabel();
        tfNomeEquipe = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelIncluirAtletas.setBorder(javax.swing.BorderFactory.createTitledBorder("Atletas a Adicionar"));

        lbAtleta1.setText("Atleta 1");
        lbAtleta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbAtleta2.setText("Atleta 2");

        lbAtleta3.setText("Atleta 3");

        lbAtleta4.setText("Atleta 4");

        lbAtleta5.setText("Atleta 5");

        cbAtleta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtleta1ActionPerformed(evt);
            }
        });

        cbAtleta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtleta2ActionPerformed(evt);
            }
        });

        cbAtleta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtleta3ActionPerformed(evt);
            }
        });

        cbAtleta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtleta4ActionPerformed(evt);
            }
        });

        cbAtleta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtleta5ActionPerformed(evt);
            }
        });

        chkAtleta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtleta1ActionPerformed(evt);
            }
        });

        chkAtleta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtleta2ActionPerformed(evt);
            }
        });

        chkAtleta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtleta3ActionPerformed(evt);
            }
        });

        chkAtleta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtleta4ActionPerformed(evt);
            }
        });

        chkAtleta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAtleta5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelIncluirAtletasLayout = new javax.swing.GroupLayout(painelIncluirAtletas);
        painelIncluirAtletas.setLayout(painelIncluirAtletasLayout);
        painelIncluirAtletasLayout.setHorizontalGroup(
            painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIncluirAtletasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(chkAtleta1)
                    .addComponent(chkAtleta2)
                    .addComponent(chkAtleta3)
                    .addComponent(chkAtleta4)
                    .addComponent(chkAtleta5))
                .addGap(18, 18, 18)
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelIncluirAtletasLayout.createSequentialGroup()
                        .addComponent(lbAtleta5)
                        .addGap(18, 18, 18)
                        .addComponent(cbAtleta5, 0, 684, Short.MAX_VALUE))
                    .addGroup(painelIncluirAtletasLayout.createSequentialGroup()
                        .addComponent(lbAtleta4)
                        .addGap(18, 18, 18)
                        .addComponent(cbAtleta4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelIncluirAtletasLayout.createSequentialGroup()
                        .addComponent(lbAtleta3)
                        .addGap(18, 18, 18)
                        .addComponent(cbAtleta3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelIncluirAtletasLayout.createSequentialGroup()
                        .addComponent(lbAtleta1)
                        .addGap(18, 18, 18)
                        .addComponent(cbAtleta1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelIncluirAtletasLayout.createSequentialGroup()
                        .addComponent(lbAtleta2)
                        .addGap(18, 18, 18)
                        .addComponent(cbAtleta2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfAtleta4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAtleta3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAtleta2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAtleta1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAtleta5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        painelIncluirAtletasLayout.setVerticalGroup(
            painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIncluirAtletasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(chkAtleta1)
                    .addComponent(lbAtleta1)
                    .addComponent(cbAtleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAtleta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfAtleta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAtleta2)
                    .addComponent(lbAtleta2)
                    .addComponent(cbAtleta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfAtleta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAtleta3)
                    .addComponent(lbAtleta3)
                    .addComponent(cbAtleta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbAtleta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAtleta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAtleta4)
                    .addComponent(chkAtleta4))
                .addGap(18, 18, 18)
                .addGroup(painelIncluirAtletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cbAtleta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAtleta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAtleta5)
                    .addComponent(chkAtleta5))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btIncluir.setText("Incluir");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        lbNomeEquipe.setText("Inclusão na Equipe: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeEquipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomeEquipe)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeEquipe)
                    .addComponent(tfNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(painelIncluirAtletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btIncluir)
                .addGap(27, 27, 27)
                .addComponent(btVoltar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(painelIncluirAtletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIncluir)
                    .addComponent(btVoltar))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        String cpf;
        int codEquipe;
        for (Component c : painelIncluirAtletas.getComponents()) {
            if (c instanceof JComboBox) {
                if (((JComboBox) c).isEnabled()) {
                    try {
                        cpf = (String) ((JComboBox) c).getSelectedItem();
                        codEquipe = Integer.parseInt(pesquisaEquipe.pesquisaEquipe(tfNomeEquipe.getText()));
                        gravaAtleta.cadastrarAtletaEquipe(cpf, codEquipe);
                        JOptionPane.showMessageDialog(this, "Atleta(s) incluidos na equipe " + tfNomeEquipe.getText() + " com sucesso");
                    } catch (SQLException ex) {
                        Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        this.dispose();
    }//GEN-LAST:event_btIncluirActionPerformed

    private void cbAtleta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtleta1ActionPerformed
        cbAtleta2.removeAllItems();
        try {
            String nome = pesquisaAtleta.pesquisaAtleta((String) cbAtleta1.getSelectedItem());
            tfAtleta1.setText(nome);
            tfAtleta1.setEnabled(false);
            ArrayList<String> atletas = pesquisaAtleta.carregaAtletas();
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    cbAtleta2.addItem(atletas.get(i));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*try {
            ArrayList<String> atletas = aBD.carregaAtletas();
            for(int i = 0; i < atletas.size(); i++){
                for(int j = 0; j < atletas.size(); j++){
                    if(cbAtleta1.getSelectedItem().equals(atletas.get(i))){
                        tfAtleta1.setText(atletas.get(i));
                    }
                }
            }
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    cbAtleta2.addItem(atletas.get(i));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_cbAtleta1ActionPerformed

    private void cbAtleta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtleta2ActionPerformed
        cbAtleta3.removeAllItems();
        try {
            String nome = pesquisaAtleta.pesquisaAtleta((String) cbAtleta2.getSelectedItem());
            tfAtleta2.setText(nome);
            tfAtleta2.setEnabled(false);
            ArrayList<String> atletas = pesquisaAtleta.carregaAtletas();
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    if (!(atletas.get(i).equals((String) cbAtleta2.getSelectedItem()))) {
                        cbAtleta3.addItem(atletas.get(i));
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*cbAtleta3.removeAllItems();
        try {
            ArrayList<String> atletas = aBD.carregaAtletas();
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    if (!(atletas.get(i).equals((String) cbAtleta2.getSelectedItem()))) {
                        cbAtleta3.addItem(atletas.get(i));
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_cbAtleta2ActionPerformed

    private void cbAtleta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtleta3ActionPerformed

        cbAtleta4.removeAllItems();
        try {
            String nome = pesquisaAtleta.pesquisaAtleta((String) cbAtleta3.getSelectedItem());
            tfAtleta3.setText(nome);
            tfAtleta3.setEnabled(false);
            ArrayList<String> atletas = pesquisaAtleta.carregaAtletas();
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    if (!(atletas.get(i).equals((String) cbAtleta2.getSelectedItem()))) {
                        if (!(atletas.get(i).equals((String) cbAtleta3.getSelectedItem()))) {
                            cbAtleta4.addItem(atletas.get(i));
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*cbAtleta4.removeAllItems();
        try {
            ArrayList<String> atletas = aBD.carregaAtletas();
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    if (!(atletas.get(i).equals((String) cbAtleta2.getSelectedItem()))) {
                        if (!(atletas.get(i).equals((String) cbAtleta3.getSelectedItem()))) {
                            cbAtleta4.addItem(atletas.get(i));
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_cbAtleta3ActionPerformed

    private void cbAtleta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtleta4ActionPerformed
        cbAtleta5.removeAllItems();
        try {
            String nome = pesquisaAtleta.pesquisaAtleta((String) cbAtleta4.getSelectedItem());
            tfAtleta4.setText(nome);
            tfAtleta4.setEnabled(false);
            ArrayList<String> atletas = pesquisaAtleta.carregaAtletas();
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    if (!(atletas.get(i).equals((String) cbAtleta2.getSelectedItem()))) {
                        if (!(atletas.get(i).equals((String) cbAtleta3.getSelectedItem()))) {
                            if (!(atletas.get(i).equals((String) cbAtleta4.getSelectedItem()))) {
                                cbAtleta5.addItem(atletas.get(i));
                            }
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*cbAtleta5.removeAllItems();
        try {
            ArrayList<String> atletas = aBD.carregaAtletas();
            for (int i = 0; i < atletas.size(); i++) {
                if (!(atletas.get(i).equals((String) cbAtleta1.getSelectedItem()))) {
                    if (!(atletas.get(i).equals((String) cbAtleta2.getSelectedItem()))) {
                        if (!(atletas.get(i).equals((String) cbAtleta3.getSelectedItem()))) {
                            if(!(atletas.get(i).equals((String) cbAtleta4.getSelectedItem()))){
                                cbAtleta5.addItem(atletas.get(i));
                            }
                        }
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_cbAtleta4ActionPerformed

    private void cbAtleta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtleta5ActionPerformed
        try {
            String nome = pesquisaAtleta.pesquisaAtleta((String) cbAtleta5.getSelectedItem());
            tfAtleta5.setText(nome);
            tfAtleta5.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbAtleta5ActionPerformed

    private void chkAtleta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtleta1ActionPerformed
        if (this.chkAtleta1.isSelected()) {
            this.cbAtleta1.setEnabled(true);
        } else {
            this.cbAtleta1.setEnabled(false);
        }
    }//GEN-LAST:event_chkAtleta1ActionPerformed

    private void chkAtleta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtleta2ActionPerformed
        if (this.chkAtleta2.isSelected()) {
            this.cbAtleta2.setEnabled(true);
        } else {
            this.cbAtleta2.setEnabled(false);
        }
    }//GEN-LAST:event_chkAtleta2ActionPerformed

    private void chkAtleta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtleta3ActionPerformed
        if (this.chkAtleta3.isSelected()) {
            this.cbAtleta3.setEnabled(true);
        } else {
            this.cbAtleta3.setEnabled(false);
        }
    }//GEN-LAST:event_chkAtleta3ActionPerformed

    private void chkAtleta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtleta4ActionPerformed
        if (this.chkAtleta4.isSelected()) {
            this.cbAtleta4.setEnabled(true);
        } else {
            this.cbAtleta4.setEnabled(false);
        }
    }//GEN-LAST:event_chkAtleta4ActionPerformed

    private void chkAtleta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAtleta5ActionPerformed
        if (this.chkAtleta5.isSelected()) {
            this.cbAtleta5.setEnabled(true);
        } else {
            this.cbAtleta5.setEnabled(false);
        }
    }//GEN-LAST:event_chkAtleta5ActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameIncluirAtletaEquipe().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameIncluirAtletaEquipe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbAtleta1;
    private javax.swing.JComboBox<String> cbAtleta2;
    private javax.swing.JComboBox<String> cbAtleta3;
    private javax.swing.JComboBox<String> cbAtleta4;
    private javax.swing.JComboBox<String> cbAtleta5;
    public javax.swing.JCheckBox chkAtleta1;
    public javax.swing.JCheckBox chkAtleta2;
    public javax.swing.JCheckBox chkAtleta3;
    public javax.swing.JCheckBox chkAtleta4;
    public javax.swing.JCheckBox chkAtleta5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAtleta1;
    private javax.swing.JLabel lbAtleta2;
    private javax.swing.JLabel lbAtleta3;
    private javax.swing.JLabel lbAtleta4;
    private javax.swing.JLabel lbAtleta5;
    private javax.swing.JLabel lbNomeEquipe;
    private javax.swing.JPanel painelIncluirAtletas;
    private javax.swing.JTextField tfAtleta1;
    private javax.swing.JTextField tfAtleta2;
    private javax.swing.JTextField tfAtleta3;
    private javax.swing.JTextField tfAtleta4;
    private javax.swing.JTextField tfAtleta5;
    public javax.swing.JTextField tfNomeEquipe;
    // End of variables declaration//GEN-END:variables

}
