package View;

import Controller.gravaBateria;
import Controller.gravaCompetidor;
import Controller.pesquisaAtleta;
import Controller.pesquisaBateria;
import Controller.pesquisaCompeticao;
import Controller.pesquisaCompetidor;
import Controller.pesquisaModalidade;
import Model.Uteis;
import Model.Competidor;
import Model.Bateria;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel
 */
public class FrameAdicionaBateria extends javax.swing.JFrame {

    Competidor competidor = new Competidor();
    Bateria bateria = new Bateria();
    Uteis funcoes = new Uteis();

    /**
     * Creates new form FrameAdicionaBateria
     */
    public FrameAdicionaBateria() throws SQLException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelBateria = new javax.swing.JPanel();
        lbData = new javax.swing.JLabel();
        lbHoraInicio = new javax.swing.JLabel();
        lbHoraFim = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        ftfHoraFim = new javax.swing.JFormattedTextField();
        ftfHoraInicio = new javax.swing.JFormattedTextField();
        ftfData = new javax.swing.JFormattedTextField();
        lbNumero = new javax.swing.JLabel();
        cbNumero = new javax.swing.JComboBox<>();
        painelCompetidores = new javax.swing.JPanel();
        chkCompetidor3 = new javax.swing.JCheckBox();
        lbCompetidor7 = new javax.swing.JLabel();
        cbCompetidor2 = new javax.swing.JComboBox<>();
        chkCompetidor5 = new javax.swing.JCheckBox();
        cbCompetidor4 = new javax.swing.JComboBox<>();
        lbCompetidor1 = new javax.swing.JLabel();
        lbCompetidor8 = new javax.swing.JLabel();
        cbCompetidor7 = new javax.swing.JComboBox<>();
        chkCompetidor4 = new javax.swing.JCheckBox();
        cbCompetidor5 = new javax.swing.JComboBox<>();
        chkCompetidor1 = new javax.swing.JCheckBox();
        chkCompetidor8 = new javax.swing.JCheckBox();
        chkCompetidor7 = new javax.swing.JCheckBox();
        cbCompetidor8 = new javax.swing.JComboBox<>();
        chkCompetidor6 = new javax.swing.JCheckBox();
        cbCompetidor3 = new javax.swing.JComboBox<>();
        lbCompetidor2 = new javax.swing.JLabel();
        lbCompetidor4 = new javax.swing.JLabel();
        cbCompetidor6 = new javax.swing.JComboBox<>();
        cbCompetidor1 = new javax.swing.JComboBox<>();
        lbCompetidor3 = new javax.swing.JLabel();
        lbCompetidor6 = new javax.swing.JLabel();
        chkCompetidor2 = new javax.swing.JCheckBox();
        lbCompetidor5 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        lbNomeCompeticao = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelBateria.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Bateria"));

        lbData.setText("Data");

        lbHoraInicio.setText("Horário de Inicio");

        lbHoraFim.setText("Horario de finalização");

        lbStatus.setText("Status");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NÃO INICIADA", "EM ANDAMENTO", "FINALIZADA" }));

        try {
            ftfHoraFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfHoraFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfHoraFimActionPerformed(evt);
            }
        });

        try {
            ftfHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            ftfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbNumero.setText("Numero");

        cbNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbNumeroMouseClicked(evt);
            }
        });
        cbNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNumeroActionPerformed(evt);
            }
        });

        chkCompetidor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor3ActionPerformed(evt);
            }
        });

        lbCompetidor7.setText("Competidor 7");

        cbCompetidor2.setEnabled(false);
        cbCompetidor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor2MouseClicked(evt);
            }
        });
        cbCompetidor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompetidor2ActionPerformed(evt);
            }
        });

        chkCompetidor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor5ActionPerformed(evt);
            }
        });

        cbCompetidor4.setEnabled(false);
        cbCompetidor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor4MouseClicked(evt);
            }
        });

        lbCompetidor1.setText("Competidor 1");

        lbCompetidor8.setText("Competidor 8");

        cbCompetidor7.setEnabled(false);
        cbCompetidor7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor7MouseClicked(evt);
            }
        });
        cbCompetidor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompetidor7ActionPerformed(evt);
            }
        });

        chkCompetidor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor4ActionPerformed(evt);
            }
        });

        cbCompetidor5.setEnabled(false);
        cbCompetidor5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor5MouseClicked(evt);
            }
        });
        cbCompetidor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompetidor5ActionPerformed(evt);
            }
        });

        chkCompetidor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor1ActionPerformed(evt);
            }
        });

        chkCompetidor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor8ActionPerformed(evt);
            }
        });

        chkCompetidor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor7ActionPerformed(evt);
            }
        });

        cbCompetidor8.setEnabled(false);
        cbCompetidor8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor8MouseClicked(evt);
            }
        });
        cbCompetidor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompetidor8ActionPerformed(evt);
            }
        });

        chkCompetidor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor6ActionPerformed(evt);
            }
        });

        cbCompetidor3.setEnabled(false);
        cbCompetidor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor3MouseClicked(evt);
            }
        });
        cbCompetidor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompetidor3ActionPerformed(evt);
            }
        });

        lbCompetidor2.setText("Competidor 2");

        lbCompetidor4.setText("Competidor 4");

        cbCompetidor6.setEnabled(false);
        cbCompetidor6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor6MouseClicked(evt);
            }
        });
        cbCompetidor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompetidor6ActionPerformed(evt);
            }
        });

        cbCompetidor1.setEnabled(false);
        cbCompetidor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbCompetidor1MouseClicked(evt);
            }
        });
        cbCompetidor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCompetidor1ActionPerformed(evt);
            }
        });

        lbCompetidor3.setText("Competidor 3");

        lbCompetidor6.setText("Competidor 6");

        chkCompetidor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompetidor2ActionPerformed(evt);
            }
        });

        lbCompetidor5.setText("Competidor 5");

        javax.swing.GroupLayout painelCompetidoresLayout = new javax.swing.GroupLayout(painelCompetidores);
        painelCompetidores.setLayout(painelCompetidoresLayout);
        painelCompetidoresLayout.setHorizontalGroup(
            painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCompetidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkCompetidor1)
                                        .addComponent(chkCompetidor2))
                                    .addComponent(chkCompetidor3))
                                .addComponent(chkCompetidor4))
                            .addComponent(chkCompetidor5))
                        .addComponent(chkCompetidor6)
                        .addComponent(chkCompetidor8, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(chkCompetidor7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbCompetidor7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor8)
                        .addGap(18, 18, 18)
                        .addComponent(cbCompetidor8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor1)
                        .addGap(18, 18, 18)
                        .addComponent(cbCompetidor1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor2)
                        .addGap(18, 18, 18)
                        .addComponent(cbCompetidor2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor3)
                        .addGap(18, 18, 18)
                        .addComponent(cbCompetidor3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor4)
                        .addGap(18, 18, 18)
                        .addComponent(cbCompetidor4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor5)
                        .addGap(18, 18, 18)
                        .addComponent(cbCompetidor5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(painelCompetidoresLayout.createSequentialGroup()
                        .addComponent(lbCompetidor6)
                        .addGap(18, 18, 18)
                        .addComponent(cbCompetidor6, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        painelCompetidoresLayout.setVerticalGroup(
            painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCompetidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCompetidor1)
                    .addComponent(cbCompetidor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCompetidor1))
                .addGap(18, 18, 18)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCompetidor2)
                        .addComponent(cbCompetidor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkCompetidor2))
                .addGap(18, 18, 18)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCompetidor3)
                        .addComponent(cbCompetidor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkCompetidor3))
                .addGap(18, 18, 18)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCompetidor4)
                        .addComponent(cbCompetidor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkCompetidor4))
                .addGap(18, 18, 18)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCompetidor5)
                        .addComponent(cbCompetidor5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkCompetidor5))
                .addGap(18, 18, 18)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCompetidor6)
                        .addComponent(cbCompetidor6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkCompetidor6))
                .addGap(18, 18, 18)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCompetidor7)
                        .addComponent(cbCompetidor7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkCompetidor7))
                .addGap(18, 18, 18)
                .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkCompetidor8)
                    .addGroup(painelCompetidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCompetidor8)
                        .addComponent(cbCompetidor8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout painelBateriaLayout = new javax.swing.GroupLayout(painelBateria);
        painelBateria.setLayout(painelBateriaLayout);
        painelBateriaLayout.setHorizontalGroup(
            painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBateriaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(painelCompetidores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbData)
                    .addComponent(lbNumero)
                    .addComponent(lbHoraInicio)
                    .addComponent(lbHoraFim)
                    .addComponent(lbStatus))
                .addGap(23, 23, 23)
                .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbStatus, 0, 126, Short.MAX_VALUE)
                    .addComponent(ftfHoraFim)
                    .addComponent(ftfHoraInicio)
                    .addComponent(ftfData)
                    .addComponent(cbNumero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelBateriaLayout.setVerticalGroup(
            painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBateriaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelCompetidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelBateriaLayout.createSequentialGroup()
                        .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNumero)
                            .addComponent(cbNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbData)
                            .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHoraInicio)
                            .addComponent(ftfHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHoraFim)
                            .addComponent(ftfHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelBateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbStatus)
                            .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btAdicionar.setText("Adicionar");
        btAdicionar.setPreferredSize(new java.awt.Dimension(90, 30));
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.setPreferredSize(new java.awt.Dimension(90, 30));
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.setPreferredSize(new java.awt.Dimension(90, 30));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lbNomeCompeticao.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lbNomeCompeticao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327)
                        .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelBateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNomeCompeticao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNomeCompeticao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(painelBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfHoraFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfHoraFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftfHoraFimActionPerformed

    private void cbCompetidor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompetidor1ActionPerformed

    }//GEN-LAST:event_cbCompetidor1ActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        int codBateria = this.inserirBateria();
        this.inserirCompetidor(codBateria);
        try {
            pesquisaCompetidor.classificaCompetidores(codBateria);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAdicionaBateria.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Competidores e bateria cadastradas com sucesso");
        btLimparActionPerformed(evt);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void chkCompetidor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor1ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor1, this.cbCompetidor1, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_chkCompetidor1ActionPerformed

    private void chkCompetidor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor2ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor2, this.cbCompetidor2, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
        /*if (this.chkCompetidor2.isSelected()) {
            this.cbCompetidor2.setEnabled(true);
            preencheComboBox(this.cbCompetidor2);
        } else {
            this.cbCompetidor2.setEnabled(false);
            cbCompetidor2.removeAllItems();
        }*/
    }//GEN-LAST:event_chkCompetidor2ActionPerformed

    private void cbCompetidor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompetidor2ActionPerformed

    }//GEN-LAST:event_cbCompetidor2ActionPerformed

    private void cbCompetidor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompetidor3ActionPerformed

    }//GEN-LAST:event_cbCompetidor3ActionPerformed

    private void cbCompetidor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor1MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor1, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor1MouseClicked

    private void cbCompetidor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor2MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor2, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor2MouseClicked

    private void cbCompetidor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor3MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor3, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor3MouseClicked

    private void cbCompetidor4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor4MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor4, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor4MouseClicked

    private void chkCompetidor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor3ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor3, this.cbCompetidor3, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
        /*if (this.chkCompetidor3.isSelected()) {
            this.cbCompetidor3.setEnabled(true);
            preencheComboBox(this.cbCompetidor3);
        } else {
            this.cbCompetidor3.setEnabled(false);
            cbCompetidor3.removeAllItems();
        }*/
    }//GEN-LAST:event_chkCompetidor3ActionPerformed

    private void chkCompetidor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor4ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor4, this.cbCompetidor4, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
        /*if (this.chkCompetidor4.isSelected()) {
            this.cbCompetidor4.setEnabled(true);
            preencheComboBox(this.cbCompetidor4);
        } else {
            this.cbCompetidor4.setEnabled(false);
            cbCompetidor4.removeAllItems();
        }*/
    }//GEN-LAST:event_chkCompetidor4ActionPerformed

    private void chkCompetidor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor5ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor5, this.cbCompetidor5, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
        /*if (this.chkCompetidor5.isSelected()) {
            this.cbCompetidor5.setEnabled(true);
            preencheComboBox(this.cbCompetidor5);
        } else {
            this.cbCompetidor5.setEnabled(false);
            cbCompetidor5.removeAllItems();
        }*/
    }//GEN-LAST:event_chkCompetidor5ActionPerformed

    private void chkCompetidor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor6ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor6, this.cbCompetidor6, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
        /*if (this.chkCompetidor6.isSelected()) {
            this.cbCompetidor6.setEnabled(true);
            preencheComboBox(this.cbCompetidor6);
        } else {
            this.cbCompetidor6.setEnabled(false);
            cbCompetidor6.removeAllItems();
        }*/
    }//GEN-LAST:event_chkCompetidor6ActionPerformed

    private void chkCompetidor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor7ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor7, this.cbCompetidor7, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
        /*if (this.chkCompetidor7.isSelected()) {
            this.cbCompetidor7.setEnabled(true);
            preencheComboBox(this.cbCompetidor7);
        } else {
            this.cbCompetidor7.setEnabled(false);
            cbCompetidor7.removeAllItems();
        }*/
    }//GEN-LAST:event_chkCompetidor7ActionPerformed

    private void chkCompetidor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompetidor8ActionPerformed
        funcoes.habilitaComboBox(this.chkCompetidor8, this.cbCompetidor8, this.painelCompetidores, this.lbNomeCompeticao, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
        /*if (this.chkCompetidor8.isSelected()) {
            this.cbCompetidor8.setEnabled(true);
            preencheComboBox(this.cbCompetidor8);
        } else {
            this.cbCompetidor8.setEnabled(false);
            cbCompetidor8.removeAllItems();
        }*/
    }//GEN-LAST:event_chkCompetidor8ActionPerformed

    private void cbCompetidor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompetidor5ActionPerformed

    }//GEN-LAST:event_cbCompetidor5ActionPerformed

    private void cbCompetidor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompetidor6ActionPerformed

    }//GEN-LAST:event_cbCompetidor6ActionPerformed

    private void cbCompetidor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompetidor7ActionPerformed

    }//GEN-LAST:event_cbCompetidor7ActionPerformed

    private void cbCompetidor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCompetidor8ActionPerformed

    }//GEN-LAST:event_cbCompetidor8ActionPerformed

    private void cbCompetidor5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor5MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor5, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor5MouseClicked

    private void cbCompetidor6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor6MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor6, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor6MouseClicked

    private void cbCompetidor7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor7MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor7, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor7MouseClicked

    private void cbCompetidor8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbCompetidor8MouseClicked
        funcoes.preencheComboBox(this.cbCompetidor8, this.lbNomeCompeticao, this.painelCompetidores, this, Integer.parseInt((String) this.cbNumero.getSelectedItem()));
    }//GEN-LAST:event_cbCompetidor8MouseClicked

    private void cbNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNumeroActionPerformed

    }//GEN-LAST:event_cbNumeroActionPerformed

    private void cbNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbNumeroMouseClicked
        this.cbCompetidor1.removeAllItems();
        this.cbCompetidor2.removeAllItems();
        this.cbCompetidor3.removeAllItems();
        this.cbCompetidor4.removeAllItems();
        this.cbCompetidor5.removeAllItems();
        this.cbCompetidor6.removeAllItems();
        this.cbCompetidor7.removeAllItems();
        this.cbCompetidor8.removeAllItems();
    }//GEN-LAST:event_cbNumeroMouseClicked

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        this.chkCompetidor1.setSelected(false);
        this.chkCompetidor2.setSelected(false);
        this.chkCompetidor3.setSelected(false);
        this.chkCompetidor4.setSelected(false);
        this.chkCompetidor5.setSelected(false);
        this.chkCompetidor6.setSelected(false);
        this.chkCompetidor7.setSelected(false);
        this.chkCompetidor8.setSelected(false);
        this.cbCompetidor1.removeAllItems();
        this.cbCompetidor2.removeAllItems();
        this.cbCompetidor3.removeAllItems();
        this.cbCompetidor4.removeAllItems();
        this.cbCompetidor5.removeAllItems();
        this.cbCompetidor6.removeAllItems();
        this.cbCompetidor7.removeAllItems();
        this.cbCompetidor8.removeAllItems();
        this.ftfData.setText("");
        this.ftfHoraInicio.setText("");
        this.ftfHoraFim.setText("");
        this.cbStatus.setSelectedIndex(0);
        this.cbNumero.setSelectedIndex(0);
    }//GEN-LAST:event_btLimparActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        try {
            FrameSelecaoBateria frameSelecao = new FrameSelecaoBateria();
            frameSelecao.lbNomeCompeticao.setText(this.lbNomeCompeticao.getText());
            frameSelecao.setName(this.getName());
            int codModalidade = pesquisaModalidade.pesquisaModalidade(this.getName());
            int codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            int numBaterias = pesquisaBateria.qtdBaterias(codModalidade, codCompeticao);
            for (int i = 1; i <= numBaterias; i++) {
                if (i == numBaterias) {
                    frameSelecao.cbBaterias.addItem("Final");
                } else {
                    frameSelecao.cbBaterias.addItem(Integer.toString(i));
                }
            }
            frameSelecao.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAdicionaBateria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrameAdicionaBateria.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdicionaBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdicionaBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdicionaBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdicionaBateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrameAdicionaBateria().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrameAdicionaBateria.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbCompetidor1;
    private javax.swing.JComboBox<String> cbCompetidor2;
    private javax.swing.JComboBox<String> cbCompetidor3;
    private javax.swing.JComboBox<String> cbCompetidor4;
    private javax.swing.JComboBox<String> cbCompetidor5;
    private javax.swing.JComboBox<String> cbCompetidor6;
    private javax.swing.JComboBox<String> cbCompetidor7;
    private javax.swing.JComboBox<String> cbCompetidor8;
    public javax.swing.JComboBox<String> cbNumero;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JCheckBox chkCompetidor1;
    private javax.swing.JCheckBox chkCompetidor2;
    private javax.swing.JCheckBox chkCompetidor3;
    private javax.swing.JCheckBox chkCompetidor4;
    private javax.swing.JCheckBox chkCompetidor5;
    private javax.swing.JCheckBox chkCompetidor6;
    private javax.swing.JCheckBox chkCompetidor7;
    private javax.swing.JCheckBox chkCompetidor8;
    private javax.swing.JFormattedTextField ftfData;
    private javax.swing.JFormattedTextField ftfHoraFim;
    private javax.swing.JFormattedTextField ftfHoraInicio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbCompetidor1;
    private javax.swing.JLabel lbCompetidor2;
    private javax.swing.JLabel lbCompetidor3;
    private javax.swing.JLabel lbCompetidor4;
    private javax.swing.JLabel lbCompetidor5;
    private javax.swing.JLabel lbCompetidor6;
    private javax.swing.JLabel lbCompetidor7;
    private javax.swing.JLabel lbCompetidor8;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbHoraFim;
    private javax.swing.JLabel lbHoraInicio;
    public javax.swing.JLabel lbNomeCompeticao;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JPanel painelBateria;
    private javax.swing.JPanel painelCompetidores;
    // End of variables declaration//GEN-END:variables

    public void inserirCompetidor(int codBateria) {
        if (codBateria != 0) {
            for (Component c : painelCompetidores.getComponents()) {
                if (c instanceof JComboBox) {
                    if (((JComboBox) c).isEnabled()) {
                        try {
                            String cpf = ((String) ((JComboBox) c).getSelectedItem()).substring(0, 14);
                            int codCompetidor = pesquisaAtleta.pesquisaCodAtleta(cpf);
                            gravaCompetidor.cadastrarNovoCompetidor(competidor, codCompetidor, codBateria);
                        } catch (SQLException ex) {
                            Logger.getLogger(FrameAdicionaBateria.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            }
        }
    }

    public int inserirBateria() {
        int codBateria = 0;
        try {
            int codModalidade = pesquisaModalidade.pesquisaModalidade(this.getName());
            int codCompeticao = pesquisaCompeticao.pesquisaCompeticao(this.lbNomeCompeticao.getText());
            
            bateria.setNumero((String) cbNumero.getSelectedItem());
            bateria.setStatus((String) cbStatus.getSelectedItem());
            bateria.setData(ftfData.getText());
            bateria.setHoraIni(ftfHoraInicio.getText());
            bateria.setHoraFim(ftfHoraFim.getText());
            codBateria = gravaBateria.cadastrarNovaBateria(bateria, codModalidade, codCompeticao);
        } catch (SQLException ex) {
            Logger.getLogger(FrameAdicionaBateria.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrameAdicionaBateria.class.getName()).log(Level.SEVERE, null, ex);
        }
        return codBateria;
    }
}
